import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/components/providers/query-provider";
import { vietnamPro } from "@/lib/fonts";
import { NuqsAdapter } from "nuqs/adapters/next/app";

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });

export const metadata: Metadata = {
	title: "Github Profile",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${vietnamPro.className} antialiased`}>
				<QueryProvider>
					<NuqsAdapter>{children}</NuqsAdapter>
				</QueryProvider>
			</body>
		</html>
	);
}
